version: "2"
services:

  # gen_prod configuration ------------------------------------------
  gen_prod_mongo:
    image: mongo:3.2.6
    volumes:
      - '../mongo/gen_prod/data:/data/db'
      - '../mongo/gen_prod/dumps:/data/mongo/dumps'
    networks:
      - gen_prod_network

  gen_prod:
    image: abernix/meteord:base
    volumes:
      - '../code/gen_prod/initial:/bundle'
      - '../mongo/gen_prod/dumps:/data/mongo/dumps'
    links:
      - 'gen_prod_mongo:mongo'
    networks:
      - gen_prod_network
    environment:
      - MONGO_URL=mongodb://mongo/gen_prod
      - ROOT_URL=http://maraisbreton.myddns.me
      - 'METEOR_SETTINGS={"public":{"analyticsSettings":{"cred":{"trackingId": "essai"}}}}'

  # gen_dev configuration ------------------------------------------
  gen_dev_mongo:
    image: mongo:3.2.6
    volumes:
      - '../mongo/gen_dev/data:/data/db'
      - '../mongo/gen_dev/dumps:/data/mongo/dumps'
    networks:
      - gen_dev_network

  gen_dev:
    image: abernix/meteord:base
    volumes:
      - '../code/gen_dev/initial:/bundle'
      - '../mongo/gen_dev/dumps:/data/mongo/dumps'
    links:
      - 'gen_dev_mongo:mongo'
    networks:
      - gen_dev_network
    environment:
      - MONGO_URL=mongodb://mongo/gen_dev
      - ROOT_URL=http://marais.dev.com


  # nginx configuration ---------------------------------------------
  nginx:
    image: nginx:1.11
    volumes:
      - '../nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '../nginx:/data/nginx'
      - '../static:/data/static'
    links:
      - 'gen_prod:gen_prod'
      - 'gen_dev:gen_dev'
    ports:
      - '80:80'
    networks:
      - gen_prod_network
      - gen_dev_network

networks:
  gen_prod_network:
  gen_dev_network:
