#!/bin/sh

echo "Mettre les données JSON dans ./mongo/gen_dev/windowsData/gen_dev (cette derniere sous directory est le nom de la base)"

# We stop the application
docker compose -p batches stop

# We start and restore Mongo
docker compose -p batches  up -d gen_dev_mongo

docker run -e FILE="/tmp/initialData" --rm --name mongoReload -it --network batches_gen_dev_network -v /media/francois/29986127-6346-4d3d-9897-ed4e3eb2ba8f/webServer/server_settings/mongo/gen_dev/windowsData:/tmp mongo:3.2.6 bash -c 'mongorestore /tmp -h "gen_dev_mongo:27017" --drop'

# We restart the application
docker compose -p batches up -d

# We list the docker-compose processes
docker compose -p batches ps

